spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mall4cloud_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: rw123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 25000
      auto-commit: true
      connection-timeout: 30000

mall4cloud:
  job:
    accessToken: 
  minio:
    endPoint: http://192.168.3.13:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: mall4cloud
