spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: mall4cloud-auth
          uri: lb://mall4cloud-auth
          predicates:
            - Path=/mall4cloud_auth/**
          filters:
            - RewritePath=/mall4cloud_auth(?<segment>/?.*), $\{segment}

        - id: mall4cloud-platform
          uri: lb://mall4cloud-platform
          predicates:
            - Path=/mall4cloud_platform/**
          filters:
            - RewritePath=/mall4cloud_platform(?<segment>/?.*), $\{segment}

        - id: mall4cloud-biz
          uri: lb://mall4cloud-biz
          predicates:
            - Path=/mall4cloud_biz/**
          filters:
            - RewritePath=/mall4cloud_biz(?<segment>/?.*), $\{segment}

mall4cloud:
  auth:
    token-header: Authorization
    token-type: Bearer
    admin-token-secret: mall4cloud-admin-secret
    user-token-secret: mall4cloud-user-secret
