spring:
  datasource:
    url: jdbc:mysql://192.168.3.13:3306/mall4cloud_auth?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: rw123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 25000
      auto-commit: true
      connection-timeout: 30000

captcha:
  water-mark: ""
